### ISSUE TITLE
clicking on idea link on twitter account raises 500 error

### ISSUE THREAD

**Issue by sivagollapalli** [punerb/ideahub#35]
After user created an Idea it sends a tweet to IdeaHub account. On that tweet if I click on link provide gives this error.

**Comment by gautamrege** [comment]
Trupti, please fix and send pull request

**Comment by gautamrege** [comment]
Trupti,
 The Show page should have the following details:

Title
Categories
- Each category should be a link that will filter out ideas by that category. (depends on #43)
  Github link: The link should be clickable and open in a new tab.
  Description
  Participants:
- All the twitter handles of the people participating.
- Each handle is a link to their twitter page
  Past Schedues
- The days when this was scheduled.
