### ISSUE TITLE
Can't participate if the user is not logged in

### ISSUE THREAD

**Issue by spatil** [punerb/ideahub#38]
Error : If user clicks on participate link and if he is not logged in then nothing happens.

Expected : It should ask for login

**Comment by gautamrege** [comment]
When the user clicks on 'Participate' and he is not logged in the, the window.location should be changed to /oauth/twitter so that the user can authenticate.

Elvin,
 Please fix this.

**Comment by rishijain** [comment]
sent pull request for above
