### ISSUE TITLE
GUI issues on Participate 

### ISSUE THREAD

**Issue by spatil** [punerb/ideahub#39]
Few GUI issues on clicking on "Participate"
1. The participants count is not incremented.
2. Need to show some kind of message to indicate the user that he is Actually participated in the event.

**Comment by rtdp** [comment]
Seems this can be closed now.
1. Seems participation count is being incremented.
2. "Participate" text changes to "Leave" on click and vice versa.

**Comment by rishijain** [comment]
1. participation count does not decrease when clicked on "Leave", only the button changes to  "Participate"
2. "Participate" does not changes to "Leave", only "Leave" changes to  "Participate".
