### ISSUE TITLE
Send TWIT under TWITTER account upon participation in some IDEA

### ISSUE THREAD

**Issue by ninad23p** [punerb/ideahub#55]
After login when user participates in some IDEA by clicking on PARTICIPATE link , send the TWIT under the TWITTER account for that user. This would help in the promotion of that IDEA as well.

TWIT sent should have link to the DETAILS of the IDEA in which the user participated.

**Comment by ninad23p** [comment]
Looks like it does sent the MENTION under the TWITTER account.

**Comment by gautamrege** [comment]
yes,
